version: "1"
services:
- type: web
  name: remdo
  runtime: docker
  repo: https://github.com/remdo-project/remdo
  branch: main
  plan: starter
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./docker/Dockerfile
  autoDeployTrigger: commit
  envVars:
    - key: PORT
      value: "8080"
  disk:
    name: remdo-data
    mountPath: /data
    sizeGB: 1
