name: Collaboration Tests
permissions:
  contents: read

on: push

jobs:
  collab-unit-tests:
    permissions:
      contents: read
      actions: write
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-pnpm

      - name: Load collaboration test env
        run: cat .github/env/collab-tests.env >> "$GITHUB_ENV"

      - name: Run collaboration unit tests
        run: pnpm run test:unit:collab
